Repository SAB-UFBA2022/backend, pull requests merged in 2022-09, with the labels that each got.

#5 Feat/login backend
  .env.example
  package-lock.json
  package.json
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/constants.ts
  src/auth/controller/auth.controller.ts
  src/auth/guards/jwt-auth.guard.ts
  src/auth/guards/local-auth.guard.ts
  src/auth/request/auth.request.ts
  src/auth/service/auth.service.spec.ts
  src/auth/service/auth.service.ts
  src/auth/strategy/jwt.strategy.ts
  src/auth/strategy/local.strategy.ts
  src/profile/controller/profile.controller.ts
  src/profile/profile.module.ts
  src/user/entities/user.entity.ts
  src/user/interface/user.interface.ts
  src/user/model/user.dto.input.ts
  src/user/model/user.response.dto.ts
  src/user/service/user.service.ts
  src/user/user.module.ts
Labels: enhancement, backend, feature

#9 env para ssl
  .gitignore
  src/database/database.module.ts
Labels: enhancement, backend

#10 4 desenvolver responsabilidades do docenteprofessoradvisor
  schema.sql
  src/advisor/advisor.module.ts
  src/advisor/controller/advisor.controller.ts
  src/advisor/dto/create-advisor.dto.ts
  src/advisor/dto/response-advisor.dto.ts
  src/advisor/dto/update-advisor.dto.ts
  src/advisor/entities/advisor.entity.ts
  src/advisor/service/advisor.service.ts
  src/app.module.ts
  src/article/controller/article.controller.ts
  src/article/service/article.service.ts
  src/user/model/user.response.dto.ts
Labels: backend, feature

#21 Feat/crud admin
  package-lock.json
  schema.sql
  src/admin/admin.module.ts
  src/admin/controller/admin.controller.ts
  src/admin/dto/create-admin.dto.ts
  src/admin/dto/response-admin.dto.ts
  src/admin/dto/update-admin.dto.ts
  src/admin/entities/admin.entity.ts
  src/admin/service/admin.service.ts
  src/app.module.ts
Labels: backend, feature

#25 Feat/saida pdf
  package-lock.json
  package.json
  relatorio.pdf
  src/article/article.module.ts
  src/article/controller/article.controller.ts
  src/article/service/article.service.ts
Labels: backend, feature

#28 Feat/login backend
  src/admin/entities/admin.entity.ts
  src/advisor/entities/advisor.entity.ts
  src/auth/auth.module.ts
  src/auth/service/auth.service.spec.ts
  src/students/entities/students.entity.ts
  src/user/interface/user.interface.ts
  src/user/model/user.dto.input.ts
  src/user/service/user.service.ts
  src/user/user.module.ts
Labels: backend, feature
