Repository SAB-UFBA2022/backend, pull requests merged in 2022-10, with the labels that each got.

#29 Fix/alterando campos student
  schema.sql
  src/auth/service/auth.service.spec.ts
  src/common/tests/TestUtil.ts
  src/students/entities/students.entity.ts
  src/students/model/student.dto.input.ts
  src/students/model/student.response.dto.ts
Labels: backend

#30 Feat/paginacao estudantes
  package-lock.json
  package.json
  src/pageable/page-meta.dto.ts
  src/pageable/page.dto.ts
  src/students/controller/students.controller.ts
  src/students/model/student.response.dto.ts
  src/students/service/student.service.spec.ts
  src/students/service/students.service.ts
Labels: backend

#33 Fix/add admin login
  src/admin/controller/admin.controller.ts
  src/admin/service/admin.service.ts
  src/auth/auth.module.ts
  src/user/service/user.service.ts
  src/user/user.module.ts
Labels: backend

#34 Fix/alteracao cadastro
  src/article/article.module.ts
  src/auth/service/auth.service.spec.ts
  src/scholarship/dto/create-scholarship.dto.ts
  src/scholarship/scholarship.module.ts
  src/scholarship/service/scholarship.service.ts
  src/students/model/student.dto.input.ts
  src/students/service/students.service.ts
  src/students/service/trash.ts
  src/students/students.module.ts
Labels: documentation, backend

#37 fix: sonar
  src/password-recovery/service/password-recovery.service.ts
Labels: backend

#38 validacoes de cadastro
  src/advisor/controller/advisor.controller.ts
  src/advisor/service/advisor.service.ts
  src/students/model/student.dto.input.ts
  src/students/service/students.service.ts
  src/students/students.module.ts
Labels: bug, backend

#39 Feat/ambiente envs
  schema.sql
  src/auth/service/auth.service.spec.ts
  src/common/tests/TestUtil.ts
  src/database/database.module.ts
  src/students/controller/students.controller.ts
  src/students/dto/student.dto.input.ts
  src/students/dto/student.response.dto.ts
  src/students/entities/students.entity.ts
  src/students/service/students.service.ts
Labels: bug, backend

#40 Feat/update final date scholarship
  .env.example
  src/scholarship/controller/scholarship.controller.ts
  src/scholarship/dto/update-scholarship.dto.ts
  src/scholarship/service/scholarship.service.ts
Labels: backend, feature

#45 migration
  schema.sql
  src/migrations/1666638134943-foreignKeyAgency.ts
Labels: bug, backend

#46 excluindo bolsa e estudante
  src/migrations/1666620187094-studentsDetails.ts
  src/scholarship/controller/scholarship.controller.ts
  src/scholarship/service/scholarship.service.ts
  src/students/controller/students.controller.ts
  src/students/service/students.service.ts
Labels: bug, backend
